stages:
  - build
#  - deploy
  - deploy-prod

build site:
  image: node:11
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build

#unit test:
#  image: node:6
#  stage: test
#  script:
#    - npm install --progress=false
#    - npm run unit

#deploy:
#  only:
#    - develop
#  image: alpine
#  stage: deploy
#  script:
#    - apk add --no-cache openssh sshpass rsync
#    - export SSHPASS=$USER_PASS 
#    - cd dist/
#    - sshpass -e scp -P 22 -o stricthostkeychecking=no -r * root@192.168.44.200:/var/www/verify-clients.onoi.kg/


deploy-prod:
  only:
    - master
  image: alpine
  stage: deploy-prod
  script:
    - apk add --no-cache openssh sshpass rsync
    - export SSHPASS=$USER_PASS
    - cd build/
    - sshpass -e scp -P 22 -o stricthostkeychecking=no -r * root@192.168.44.200:/var/www/verify-clients.onoi.kg/
